#ifndef QTPLUGINSMANAGER_GLOBAL_H
#define QTPLUGINSMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTPLUGINSMANAGER_LIBRARY)
#  define QTPLUGINSMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTPLUGINSMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTPLUGINSMANAGER_GLOBAL_H
